version: '3'

services:
  db:
    image: mysql:8.0
    env_file:
      - ./.envs/.mysql
  web:
    build: .
    command: >
      sh -c "sleep 10 && 
             python manage.py migrate
             python manage.py runserver 0.0.0.0:8080"
    env_file:
      - ./.envs/.mysql
    volumes:
      - ./practical_web_development-main/:/code
      - ./practical_web_development-main/static:/static
    ports:
      - "8080:8080"
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - ./practical_web_development-main/static:/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static: